# Generated by Django 5.2.15 on 2026-06-30 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_location_educationcard_visitcard_transitleg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_cards', models.ManyToManyField(blank=True, related_name='itineraries', to='itineraries.educationcard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttachedVisitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('visit_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attached_itineraries', to='itineraries.visitcard')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_visit_cards', to='itineraries.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedTransitLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('transit_leg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attached_itineraries', to='itineraries.transitleg')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_transit_legs', to='itineraries.itinerary')),
            ],
        ),
    ]
